server:
  port: 5000
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/oodachi-querydsl?currentSchema=public
    username: postgres
    password: 123456
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    # 执行错误时, 清空数据库重新运行迁移操作, 仅适用于本地开发!!!
    clean-disabled: false
    clean-on-validation-error: true